// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestBackendTask.Context;

#nullable disable

namespace TestBackendTask.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20220709105408_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("TestBackendTask.Context.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ToDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("TestBackendTask.Context.Entities.ReportResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CountSignIn")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("ReportResults");
                });

            modelBuilder.Entity("TestBackendTask.Context.Entities.ReportResult", b =>
                {
                    b.HasOne("TestBackendTask.Context.Entities.Report", "Report")
                        .WithOne("Result")
                        .HasForeignKey("TestBackendTask.Context.Entities.ReportResult", "ReportId");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("TestBackendTask.Context.Entities.Report", b =>
                {
                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
